version: '3.9'

## docker-compose -p alessio-arena-stack up -d
## docker-compose -p alessio-arena-stack down

services:

    alessio-arena-api:
        container_name: alessio-arena-api
        image: nginx:alpine
        environment:
          VIRTUAL_HOST: alessio-arena-api.internal.local
          VIRTUAL_PORT: 443
          VIRTUAL_PROTO: https
        expose:
            - 443
        volumes:
            - ./:/usr/share/nginx/html
            - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./ssl/certs/localhost.crt:/etc/ssl/certs/localhost.crt
            - ./ssl/private/localhost.key:/etc/ssl/private/localhost.key
        networks:
            - nginx-proxy

    alessio-arena-fpm-php:
        container_name: alessio-arena-fpm-php
        image: alessio-arena-fpm-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/share/nginx/html
            - ./conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        expose:
            - 9000
        networks:
            - nginx-proxy

    alessio-arena-db:
        container_name: alessio-arena-db
        image: mariadb:10.6.1-focal
        restart: always
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: xz32NNgr45!
        volumes:
            - ./db-data/:/var/lib/mysql
        expose:
            - 3306
        networks:
            - nginx-proxy

            
networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
